CRUD Module Article
nurisakbar/marketplace pull request #7
Opened 2021-07-29 16:15 UTC by dedyods

1. Model & Migration
2. Api Crud Model Article

2021-07-29 16:26 UTC, nurisakbar requested changes

2021-07-29 16:26 UTC, nurisakbar commented on app/Http/Requests/UpdateArticleRequest.php
> +            'image'         =>  'required|image|mimes:jpeg,jpg,png|max:2000'
udah coba update article dengan mengupload image ?

2021-07-29 16:26 UTC, nurisakbar commented on app/Http/Resources/ArticleResource.php
> +        return parent::toArray($request);
silahkan tambahkan id,title,slug,article,category,image dan active nya.
untuk category silahkan buat relasi ke model category.

2021-07-30 03:58 UTC, dedyods commented on app/Http/Requests/UpdateArticleRequest.php
> +            'image'         =>  'required|image|mimes:jpeg,jpg,png|max:2000'
sudah mas sudah ditest, bisa melakukan update dengan melakukan testing dengan update image

2021-07-30 04:33 UTC, dedyods commented on app/Http/Resources/ArticleResource.php
> +        return parent::toArray($request);
baik mas, sudah ditambahkan.

2021-07-30 04:36 UTC, nurisakbar requested changes

2021-07-30 04:36 UTC, nurisakbar commented on app/Http/Requests/UpdateArticleRequest.php
> +            'image'         =>  'required|image|mimes:jpeg,jpg,png|max:2000'
sip, udah pakai post ya, kalau pakai put gak bisa soalnya

2021-07-30 04:36 UTC, nurisakbar commented on app/Http/Controllers/ArticleController.php
> +    protected $fieldSearchable = [
silahkan tambahkan informasi cara melakukan request artikel dengan filter pencarian berdasarkan judul pada deskripsi pull request.
over all udah OK.

2021-07-30 04:36 UTC, nurisakbar commented on app/Http/Controllers/ArticleController.php
> +        // $article = $this->articleRepository->all();
komentar komentar ini kalau tidak dipakai dihapus aja.

2021-07-30 05:59 UTC, dedyods commented on app/Http/Controllers/ArticleController.php
> +    protected $fieldSearchable = [
Yang ini belum nemu mas solusinya, maaf mas, ini kayaknya ke push lupa dihapus.

2021-07-30 09:25 UTC, dedyods commented on app/Http/Controllers/ArticleController.php
> +        // $article = $this->articleRepository->all();
ok siap mas, makasih masukan nya...

2021-07-30 10:35 UTC, nurisakbar commented on app/Http/Controllers/ArticleController.php
> +    protected $fieldSearchable = [
@dedyods : ayo semangat ngulik dulu 👍

2021-07-31 07:05 UTC, nurisakbar requested changes

2021-07-31 07:05 UTC, nurisakbar commented on app/Http/Controllers/ArticleController.php
> +        $data = $articleService->create($request);
ini di ubah aja sesuai dengan kesepatakan kita di grub.
        $data = $articleService->create($request);
       $article = $this->articleRepository->update($data, $id);
        return new ArticleResource($article);

2021-07-31 07:05 UTC, nurisakbar commented on app/Http/Controllers/ArticleController.php
> +        $data = $articleService->create($request);
ini juga sama seperti yang di update

2021-07-31 07:05 UTC, nurisakbar commented on app/Repositories/ArticleRepository.php
> +// class ArticleRepository extends BaseRepository {
komentar2 yang gak dipakai ini dihapus aja

2021-07-31 07:05 UTC, nurisakbar commented on app/Repositories/ArticleRepository.php
> +//     public function boot(){
function function yang gak dipakai dihapus aja, jangan di comment

2021-07-31 07:05 UTC, nurisakbar commented on database/migrations/2021_07_29_135210_create_articles_table.php
> +			$table->string('title');
rapikan indentasi nya biar rapi 😄

2021-07-31 07:05 UTC, nurisakbar commented on app/Http/Controllers/ArticleController.php
> +        return new ArticleResource($this->articleRepository->find($id));
ini dibuat sama aja ya :
$article = $this->articleRepository->find($id);
return new ArticleResource($article);

2021-07-31 07:26 UTC, merged