module-store
nurisakbar/marketplace pull request #8
Opened 2021-07-29 17:36 UTC by nanung91

mohon izin koreksi ya mas.terimakasih

2021-07-30 03:38 UTC, nurisakbar requested changes

2021-07-30 03:38 UTC, nurisakbar commented on app/Http/Controllers/StoreController.php
> +            $store = $this->storeRepository->findWhere(['name' => $request->type]);
ini kenapa ngebaca request type ya ?
terus jika ingin mencari sebaiknya pakai like jangan find where, karna findWhere artinya value dari nama store nya harus sesuai.

2021-07-30 03:38 UTC, nurisakbar commented on app/Http/Controllers/StoreController.php
> +        return new StoreResource($this->storeRepository->update($storeService->create($request), $id));
sebaiknya parameter dibuatkan terpisah saja biar lebih gampang dibaca
$data = $storeService xxxxx
return new storeResource($this->storeService->update($data,$id));

2021-07-30 03:38 UTC, nurisakbar commented on app/Http/Requests/CreateStoreRequest.php
> +            'user_id'       =>  'required',
sebaiknya parameter id jangan dikirim, karna memungkinkan orang lain melakukan request dengan mengirimkan id_user orang lain.

saran : gunakan fungsi Auth::user()->id pada storeService method create

2021-07-30 03:38 UTC, nurisakbar commented on app/Http/Requests/UpdateStoreRequest.php
> +            'user_id'       =>  'required',
disini juga sama seperti yang create

2021-07-30 03:38 UTC, nurisakbar commented on app/Http/Requests/UpdateStoreRequest.php
> +            'logo'          =>  'required',
method PUT tidak bisa upload file, jadi menjadikan mandatory logo pada proses update dan method PUT membuat tidak bisa melakukan request update

2021-07-30 03:38 UTC, nurisakbar commented on app/Http/Resources/StoreResource.php
> +            'user_id'        =>  $this->user_id,
user_id sepertinya gak perlu ditampilkan

2021-07-31 04:53 UTC, nanung91 commented on app/Http/Controllers/StoreController.php
> +            $store = $this->storeRepository->findWhere(['name' => $request->type]);
ada alternatif g mas kalo di laravel kan where('name','like',$request['name'])..kalo di repository pake apakah?terimakasih

2021-07-31 07:45 UTC, nurisakbar commented on app/Http/Controllers/StoreController.php
> +            $store = $this->storeRepository->findWhere(['name' => $request->type]);
coba cek controller article mas, udah ada yang berhasil

2021-08-06 02:45 UTC, merged