CRUD harvest
nurisakbar/marketplace pull request #9
Opened 2021-07-30 08:01 UTC by rizkypujiraharja

- delete images
- add image
- api crud

2021-07-30 10:25 UTC, nurisakbar commented on database/migrations/2021_07_30_074742_drop_images_add_image_harvest_table.php
> +        Schema::table('harvests', function (Blueprint $table) {
images ini mandatory, jadi nanti di field images akan di simpan list gambar panen.
teknisnya client mengirimkan multiple images ( maximal 4 ) sekaligus.
semua image itu akan di upload dan nama file nya akan disimpan di dalam array.

sebelum disimpan ke field images, data array yang menampung list images tadi akan di serialize dulu ( https://www.php.net/manual/en/function.serialize.php )

2021-07-30 10:25 UTC, nurisakbar commented on database/migrations/2021_07_30_074742_drop_images_add_image_harvest_table.php
> +        Schema::table('harvests', function (Blueprint $table) {
yang lain udah OK

2021-07-30 10:26 UTC, nurisakbar commented on app/Http/Controllers/HarvestController.php
> +        $harvests = $this->harvestRepository->all();
tambahkan fungsional agar list harvest bisa dicari berdasarkan field title, coba pelajari push criteria

2021-08-02 05:17 UTC, rizkypujiraharja commented on database/migrations/2021_07_30_074742_drop_images_add_image_harvest_table.php
> +        Schema::table('harvests', function (Blueprint $table) {
sudah saya tambahkan serialize untuk menyimpan data gambarnya juga validasi maksimal 4 gambar sekali upload

:)

2021-08-02 05:17 UTC, rizkypujiraharja commented on app/Http/Controllers/HarvestController.php
> +        $harvests = $this->harvestRepository->all();
updated mas, terima kasih masukannya

2021-08-02 05:34 UTC, nurisakbar requested changes

2021-08-02 05:34 UTC, nurisakbar commented on app/Http/Controllers/HarvestController.php
> +        return new HarvestResource($this->harvestRepository->find($id));
biar seragam dengan create, gimana kalau sebaiknya dibuat gini ?
$harvest = $this->harvestRepository->find($id);
return new HarvestResource($harvest);

2021-08-02 12:55 UTC, merged